---
- name: Create an empty folder and download jenkins.war and change the permissions etc
  hosts: all
  tasks:
    - name: create an empty folder
      file:
        name: /tmp/myfolder
        state: directory
    - name: Download the jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.555.1/jenkins.war
        dest: /tmp/myfolder
    - name: Change owner,group and permissions on the jenkins.war file
      file:
        name: /tmp/myfolder/jenkins.war
        mode: 750
        owner: sai
        group: root
...
