---
- name: Implementing tags
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      tags: 
        - install
        - apache_install
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
      tags:
        - restart
        - always
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: no
      tags: 
        - install
        - tomcat_install
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted
      tags: 
        - restart
        - never
