---
- name: Implementing handlers
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check url response
    - name: Edit the index.html file
      copy:
        content: "Welcome to  IntelliQIT"
        dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: check url response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.10.35
        - http://172.31.3.91
...

