---
- name: Create multiple users and copy files into users home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: ramesh,b: intelliqit,c: /home/ramesh}
        - {a: anesh,b: intelliqit,c: /tmp/anesh}
    - name: Copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/ramesh}
        - {a: /etc/group,b: /tmp/anesh}
...
